---
- name: Install node_exporter on Windows
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Download node_exporter archive
      win_get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.windows-amd64.tar.gz"
        dest: C:\Temp\node_exporter.tar.gz

    - name: Extract node_exporter archive
      win_shell: |
        Expand-Archive -Path C:\Temp\node_exporter.tar.gz -DestinationPath C:\Temp
      args:
        executable: powershell.exe

    - name: Copy node_exporter files to installation directory
      win_command: |
        Copy-Item -Path C:\Temp\node_exporter-1.2.2.windows-amd64\node_exporter.exe -Destination C:\Program Files\node_exporter\node_exporter.exe
      args:
        creates: C:\Program Files\node_exporter\node_exporter.exe

    - name: Create node_exporter service
      win_shell: |
        New-Service -Name "node_exporter" -BinaryPathName "C:\Program Files\node_exporter\node_exporter.exe" -DisplayName "Node Exporter"
      args:
        executable: powershell.exe
      ignore_errors: yes  # Ignore if service already exists

    - name: Start node_exporter service
      win_service:
        name: "node_exporter"
        state: started
